config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :restaurants, only: %i[index show] do
    resources :bookings, only: [:create]
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :restaurants
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  belongs_to :customer
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  remove_reference :customers, foreign_key: true
  belongs_to :customer
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def restaurant
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/booking/restaurant.html.erb
<h1>Booking#restaurant</h1>
<p>Find me in app/views/booking/restaurant.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aplicaciontest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Restaurants</h1>

<%= link_to 'Voir les restaurants', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Voici tous les restaurants</h1>
<%= link_to 'Voir le restaurant', restaurant_path(@restaurants) %>

app/views/restaurants/show.html.erb
<h1>View show restaurant</h1>